name: moneyvibes
description: A modern financial tracking app focused on user experience, built with Flutter.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.0.0
  animate_do: ^3.0.0
  sqflite: ^2.0.0+3
  path: ^1.8.0
  flutter_local_notifications: ^17.0.0
  provider: ^6.0.0
  intl: ^0.19.0
  fl_chart: ^0.67.0
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true